### ISSUE TITLE
Spec 11 分數以玩家對怪物造成的傷害、玩家所受到的傷害以及擊殺怪物的數量為評定標準。

### ISSUE THREAD

**Issue by jaidTw** [jaidTw/FatelTale#12]
討論：
* 分數公式

**Comment by hk19960522** [comment]
目前構想 : 
         分數 = 對怪物造成的傷害 + 擊殺怪物時得到相當於該怪物血量一半的分數 - 受到的傷害 - 死亡時分數減半

之後視情況修改
