### ISSUE TITLE
Player, Monster 與 Collider 和其他內含於這兩種 Class 的其他類別的屬性值

### ISSUE THREAD

**Issue by hk19960522** [jaidTw/FatelTale#15]
Player 和 Monster 內的一些類別有時候會和他們本身共用某些值，我們要不要把這些值的型別從 int, float 改成 Integer, Float 呢 ?

Integer 和 Float 算是 Object 的一種，所以在某個地方改變時，所以指向它的變數也會一起改，這樣是不是比較符合我們的需求 ?

**Comment by ChiuTeHao** [comment]
能麻煩舉例說明嗎?只要符合需求當然可以考慮

**Comment by hk19960522** [comment]
例如 Player 和 Monster 都有攻擊速度，而 Player 和 Monster 的下面的東西 ( 例如 子彈和發射器 ) 也同樣需要這些的東西，那這樣我們用 Integer 和 Float 就可以同時更新了

**Comment by hk19960522** [comment]
後來發現 Integer 並不是 call by reference
因此還是將變數放到較底層的類別中

**Comment by hk19960522** [comment]
寫了 Collider 和 Emitter 後發現他們需要一堆 player 的東西，所以我希望 player 的位置和方向可以改成 Java 內建的 Point ( 類似 C++ 的 pair<int, int> ， 也是存兩個數字 ) ，而 Collider 和 Emitter 以及 player 就可以同樣修改了，我試過了，可以改

這樣子如何?

**Comment by ChiuTeHao** [comment]
OK，收到，不過我得先查一下Point用法，才會改code

**Comment by hk19960522** [comment]
OK
