### ISSUE TITLE
移動方式以及攻擊方式的TCP傳遞

### ISSUE THREAD

**Issue by vincent50117** [jaidTw/FatelTale#16]
我們之前上課好像有討論說
移動要改成按下傳TCP給SERVER，放開再傳
以減少TCP高頻率的傳輸

那攻擊是否也要改成這樣子的傳遞法
按下之後傳TCP將server端的角色改成攻擊狀態
直到放開再傳一次TCP回到正常狀態

或者是要DOM這邊增加attack  speed然後計算時間

**Comment by jaidTw** [comment]
我覺得可以

**Comment by hk19960522** [comment]
那麼這樣 Player 必須加上兩個 boolean 變數，一個是判斷是否正在移動以及是否正在攻擊
而攻擊和移動判定就交給 PEM 負責 ?

**Comment by jaidTw** [comment]
對，PEM檢查是不是攻擊、移動狀態
移動的話可能就是根據速度去算位置
攻擊的話我們可能要討論一下最小的時間間隔?

**Comment by hk19960522** [comment]
我覺得這部分可以等到遊戲可以連線移動後再調就好，因為計算攻擊間格和判斷移動的算法是一模一樣的

**Comment by vincent50117** [comment]
突然想到這樣子我這邊需要紀錄狀態嗎、還是交由UIM傳TCP就好

**Comment by hk19960522** [comment]
這樣好像就不用了
