### ISSUE TITLE
當玩家按下攻擊或移動按鍵，UIM要呼叫TCP和UDP哪些function??

### ISSUE THREAD

**Issue by ChiuTeHao** [jaidTw/FatelTale#18]
如題，當玩家按下攻擊或移動按鍵，UIM要呼叫TCP和UDP哪些function，傳送玩家的行為??

**Comment by jaidTw** [comment]
你可以把所有可能的行為整理給我嗎？

**Comment by ChiuTeHao** [comment]
UIM應該會需要TCP提供四個function，傳送以下行為到server端，參數分別如下:
玩家ID+移動按鍵按下
玩家ID+攻擊按鍵按下
玩家ID+移動按鍵放開
玩家ID+攻擊按鍵放開

**Comment by jaidTw** [comment]
TCPClient現在提供了兩個function
```java
public void keyDown(int code)
public void keyRelease(int code)
```
參數code可能的值定義在tcp/codes.java中
可以用
```
import tcp.codes
codes.MOVELEFT
codes.MOVERIGHT
codes.MOVEUP
codes.MOVEDOWN
codes.ATTACK
```
取得

**Comment by jaidTw** [comment]
希望CDC提供兩個function，分別對應keydown跟keyrelease
參數為int，值是上面列出的code
