### ISSUE TITLE
TCP 新增功能要求

### ISSUE THREAD

**Issue by hk19960522** [jaidTw/FatelTale#20]
目前需要 TCP 有以下功能 : 

Server 端 : PEM 或 CDC ( 尚未決定 ) 會在增加以及刪除 monster, projector 或 item 時，以 TCP 的方式通知 Client 端，Server 會傳入 String ( 代表種類 ) 以及 ID，Client 端根據接收到的訊息去呼叫 DOM 中對應的 function，至於 DOM 有啥 function，就請 吳承諭 說明

**Comment by vincent50117** [comment]
刪除的部分沒有問題
可是我剛剛突然想到、如果新增一個空的進DOM
SPRITERE在呼叫DOM的東西的時候也會拉出來
這樣就會產生拉到不能畫的東西

**Comment by jaidTw** [comment]
這個應該很快就好
先給你prototype
```java
public void delete(int ID, int type)
```
type我這邊可能會定義幾個常數，而不要用字串
然後不同種類物件的ID會重複嗎?不然其實也不用傳type

**Comment by hk19960522** [comment]
@vincent50117 你可以加一個條件去做判斷?

@jaidTw 不同種類的物件 ID 是會重複的

**Comment by vincent50117** [comment]
@hk19960522  那個type不是就是用來分物件的嗎
刪除的時候根本沒差啊、有id就直接砍掉了
新增是為了指令方便的話其實dom這邊除了 playerInfo 以外都是同個格式
要加個參數只用一次確認是不是已經有數據也不是不行就是了

**Comment by hk19960522** [comment]
最後確認
刪除和增加時 server 會給兩個參數，分別代表 type 和 ID
client 根據接受到的訊息來呼叫 DOM 的 function

**Comment by jaidTw** [comment]
那就維持上面的prototype
