### ISSUE TITLE
Monster的toString格式

### ISSUE THREAD

**Issue by ChiuTeHao** [jaidTw/FatelTale#23]
Monster的 toString() 格式:
"Monster " + 怪獸 ID + " " + 怪獸 x 座標 + " " + 怪獸 y 座標 + " " +  怪獸方向 ( String ) + " " +  asset_index

**Comment by hk19960522** [comment]
Projector toString() : 
"Projector " + ID + " " + x 座標 + " " + y 座標 + " " + x 方向座標 + " " + y 方向座標 + " " +  asset_index

**Comment by hk19960522** [comment]
更新格式

**Comment by hk19960522** [comment]
更新格式
